### ISSUE TITLE
trainin run code problem :(

### ISSUE THREAD

**Issue by alperzorlu** [seraj94ai/Train-Object-Detection-Classifier#1]
Hello Dear Seraj, ı have problem 

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\builders\model_builder.py", line 30, in <module>
    from object_detection.models import faster_rcnn_inception_resnet_v2_feature_extractor as frcnn_inc_res
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\models\faster_rcnn_inception_resnet_v2_feature_extractor.py", line 28, in <module>
    from nets import inception_resnet_v2
ModuleNotFoundError: No module named 'nets'

pls help me..

**Comment by alperzorlu** [comment]
Rasha, ı have run to again path slim code is ok , but ı have  another problem : 
(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:126: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
W1027 16:43:21.643006 16784 tf_logging.py:126] From C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:126: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
WARNING:tensorflow:From C:\tensorflow1\models\research\object_detection\legacy\trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W1027 16:43:21.939810 16784 tf_logging.py:126] From C:\tensorflow1\models\research\object_detection\legacy\trainer.py:265: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 279, in train
    train_config.prefetch_queue_capacity, data_augmentation_options)
  File "C:\tensorflow1\models\research\object_detection\legacy\trainer.py", line 59, in create_input_queue
    tensor_dict = create_tensor_dict_fn()
  File "train.py", line 121, in get_next
    dataset_builder.build(config)).get_next()
  File "C:\tensorflow1\models\research\object_detection\builders\dataset_builder.py", line 123, in build
    num_additional_channels=input_reader_config.num_additional_channels)
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 297, in _init_
    default_value=''),
  File "C:\tensorflow1\models\research\object_detection\data_decoders\tf_example_decoder.py", line 59, in _init_
    label_map_proto_file, use_display_name=False)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 164, in get_label_map_dict
    label_map = load_labelmap(label_map_path)
  File "C:\tensorflow1\models\research\object_detection\utils\label_map_util.py", line 136, in load_labelmap
    text_format.Merge(label_map_string, label_map)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 874, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1237, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1252, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1277, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_encoding.py", line 103, in CUnescape
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
  File "C:\Users\Alper Z\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_encoding.py", line 103, in <genexpr>
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
IndexError: list index out of range﻿
